### ISSUE TITLE
Merge this repo to BlendingEditor

### ISSUE THREAD

**Issue by warpech** [Starcounter/starcounter-layout-html-editor#21]
@tomalec, what would you say about merging this repo to BlendingEditor?

**Comment by tomalec** [comment]
To reduces repolepsy, or is there some other reason?

It complicates testing (at least for me setting up travis is easier that running app tests in TC. Also by keeping this element outside of the app, we make it easier to use it in 

- alternative app,
- browser extension,
- inline in devtools.

**Comment by warpech** [comment]
To reduce repolepsy.

To do the testing you will be able to use `src/BlendingEditor/wwwroot/BlendingEditor/elements/starcounter-layout-html-editor` directory as you use this repo. We can configure Travis to observe it.

We can turn on WCT testing in TeamCity as well.

We don't have a use case for any of the bullet points right now. I'd rather not optimize our workflow for things that we are not doing.

**Comment by tomalec** [comment]
In my opinion having separate repo forces modularization, with an element in an app it would be easier to hide hidden spaghetti wiring.

We could apply same reasoning to `<starcounter-include>`, `<starcounter-upload>`, `<palindrom-client>`, `<palindrom-redirect>` and merge them to the StarcounterClientFiles. 
Even though `<juicy-markdown>` or `<juicy-ace-editor>` was initially created for a specific app, thanks to the fact we separated it to it's own repo it is now used by other apps, like Content. I believe WYSIWYG+code HTML editor could be a useful component not only for Blending, but for all kinds of CMS apps.

I agree we can move composition & starcounter-include wiring related part to Blending app's element - ~half of `starcounter-layout-html-editor.html`, but I think having (better version of) `juicy-simple-visual-html-editor.html` and remaining half of `stracounter-layout-...` could make future develoment easier.

> We don't have a use case for any of the bullet points right now

We don't. But I think we should plan those. I think having a browser extension instead of CompositionEditor app could have solve the problems we had in the past - brush icon in every partial view changing it's id.

If you feel really strong need for reducing repolapsy in this area, please merge it there. But I'd keep those use cases for the discussion about simplifying Blending, Surfaces, etc.

**Comment by warpech** [comment]
Since you insist, let's keep it as it is. You are the responsible person for this repo and I am just trying to find ways to make us the most productive. Other goals don't matter as much as productivity.

I have asked Patryk to change the version in https://github.com/Starcounter/Blending/blob/2ca5d610047b853a43ccb35ef7515ecd9e7804fd/src/BlendingEditor/bower.json#L23 from `^0.0.3` to `*`, so that we don't have to release versions of `starcounter-layout-html-editor`.

---

> In my opinion having separate repo forces modularization, with an element in an app it would be easier to hide hidden spaghetti wiring.

This did not stop us from having spaghetti code that uses `starcounter-include` private methods, so I don't think that it *forces* anything. Modularisation vs spaghetti is one thing and monorepo vs repolepsy is another thing.

**Comment by warpech** [comment]
Today on a Hangout we agreed to merge this into BlendingEditor

**Comment by warpech** [comment]
Closing as done in https://github.com/Starcounter/Blending/pull/341
